Homework4
Ren4t/java1_2020 pull request #2
Opened 2020-08-30 20:37 UTC by Ren4t

2020-09-01 21:56 UTC, OKrylov requested changes
В целом ход мысли верный, но лучше доработать до более универсального решения

2020-09-01 21:56 UTC, OKrylov commented on src/homework4/TicTacToe.java
> +                if (j + 3 < SIZE && map[i][j] == symbol && map[i][j + 1] == symbol && map[i][j + 2] == symbol && map[i][j + 3] == symbol) {
почему именно 3?

2020-09-01 21:56 UTC, OKrylov commented on src/homework4/TicTacToe.java
> +                if (i + 3 < SIZE && map[i][j] == symbol && map[i + 1][j] == symbol && map[i + 2][j] == symbol && map[i + 3][j] == symbol) {
стоит задать константу, сколько клеток нужно для победы, и пробегаться циклами, используя счетчик, сколько подряд одинаковых символов мы встретили. Если встречаем другой/пустой - обнуляем. И в конце сравниваем количество с тем, которое нам требуется

2020-09-01 21:56 UTC, OKrylov commented on src/homework4/TicTacToe.java
> +    private static void aiTurn() {
просмотр всех частных случаев - не самая лучшая идея. С ростом размерности игры придется модернизировать и данный код. Попробуйте смоделировать ход противника по каждой пустой клетке, после этого выполнить проверку на победу. Если да - это та клетка, которую стоит блокировать

2020-09-02 18:54 UTC, Ren4t commented on src/homework4/TicTacToe.java
> +                if (j + 3 < SIZE && map[i][j] == symbol && map[i][j + 1] == symbol && map[i][j + 2] == symbol && map[i][j + 3] == symbol) {
чтоб не выскочить за приделы массива, проверить хотел победу четырех крестиков

2020-09-02 18:55 UTC, Ren4t commented on src/homework4/TicTacToe.java
> +    private static void aiTurn() {
Ясно.эт уже понял

2020-09-30 18:05 UTC, merged